In [1]:
import psycopg2 as pg2
import datetime as datetime
import pandas as pd

In [6]:
df = pd.read_csv('LBMP Compiled.csv', header=0, keep_default_na=False, na_values='.')

In [ ]:
format = lambda x: str(x)[:-3]

In [122]:
df['DateOfYear'] = df['Date'].map(format)

In [123]:
df

           Date  Hour Zone Name   LBMP DateOfYear
0        8/6/14     0    CAPITL  27.35        8/6
1        8/6/14     1    CAPITL  23.19        8/6
2        8/6/14     2    CAPITL  20.53        8/6
3        8/6/14     3    CAPITL  19.79        8/6
4        8/6/14     4    CAPITL  20.18        8/6
5        8/6/14     5    CAPITL  23.03        8/6
6        8/6/14     6    CAPITL  26.86        8/6
7        8/6/14     7    CAPITL  29.30        8/6
8        8/6/14     8    CAPITL  29.73        8/6
9        8/6/14     9    CAPITL  34.10        8/6
10       8/6/14    10    CAPITL  35.62        8/6
11       8/6/14    11    CAPITL  38.65        8/6
12       8/6/14    12    CAPITL  39.42        8/6
13       8/6/14    13    CAPITL  40.93        8/6
14       8/6/14    14    CAPITL  42.71        8/6
15       8/6/14    15    CAPITL  44.51        8/6
16       8/6/14    16    CAPITL  45.82        8/6
17       8/6/14    17    CAPITL  41.92        8/6
18       8/6/14    18    CAPITL  38.10        8/6
19       8/6/14    19    CAPITL  36.16        8/6
20       8/6/14    20    CAPITL  37.24        8/6
21       8/6/14    21    CAPITL  35.53        8/6
22       8/6/14    22    CAPITL  29.69        8/6
23       8/6/14    23    CAPITL  27.24        8/6
24       8/7/14     0    CAPITL  26.09        8/7
25       8/7/14     1    CAPITL  20.98        8/7
26       8/7/14     2    CAPITL  18.24        8/7
27       8/7/14     3    CAPITL  17.15        8/7
28       8/7/14     4    CAPITL  17.47        8/7
29       8/7/14     5    CAPITL  20.71        8/7
...         ...   ...       ...    ...        ...
398130  8/14/17    18      WEST  29.89       8/14
398131  8/14/17    19      WEST  27.84       8/14
398132  8/14/17    20      WEST  27.04       8/14
398133  8/14/17    21      WEST  24.65       8/14
398134  8/14/17    22      WEST  20.42       8/14
398135  8/14/17    23      WEST  18.90       8/14
398136  8/15/17     0      WEST  19.60       8/15
398137  8/15/17     1      WEST  15.39       8/15
398138  8/15/17     2      WEST  14.89       8/15
398139  8/15/17     3      WEST  13.43       8/15
398140  8/15/17     4      WEST  14.70       8/15
398141  8/15/17     5      WEST  15.95       8/15
398142  8/15/17     6      WEST  18.40       8/15
398143  8/15/17     7      WEST  21.74       8/15
398144  8/15/17     8      WEST  23.70       8/15
398145  8/15/17     9      WEST  27.80       8/15
398146  8/15/17    10      WEST  33.02       8/15
398147  8/15/17    11      WEST  38.00       8/15
398148  8/15/17    12      WEST  45.00       8/15
398149  8/15/17    13      WEST  49.92       8/15
398150  8/15/17    14      WEST  47.53       8/15
398151  8/15/17    15      WEST  50.11       8/15
398152  8/15/17    16      WEST  46.02       8/15
398153  8/15/17    17      WEST  39.51       8/15
398154  8/15/17    18      WEST  33.17       8/15
398155  8/15/17    19      WEST  31.34       8/15
398156  8/15/17    20      WEST  29.63       8/15
398157  8/15/17    21      WEST  27.44       8/15
398158  8/15/17    22      WEST  23.12       8/15
398159  8/15/17    23      WEST  20.66       8/15

[398160 rows x 5 columns]

In [10]:
hours = df.Hour.unique()

In [13]:
zones = df["Zone Name"].unique()

In [50]:
days = df.DateOfYear.unique()

In [109]:
records = []
for zone in zones:
    print("zone: " + zone)
    zoneDf = df[df['Zone Name'] == zone]
    for hour in hours:
        #print('Hour:' + str(hour))
        hourDf = zoneDf[zoneDf.Hour == hour]
        for day in days:
            #print('day:' + day)
            records.append({  'Date':day,
                              'Hour':hour,
                              'Zone':zone,
                              'LBMP Mean':hourDf[hourDf.DateOfYear == day].LBMP.mean()})

zone: CAPITL
zone: CENTRL
zone: DUNWOD
zone: GENESE
zone: H Q
zone: HUD VL
zone: LONGIL
zone: MHK VL
zone: MILLWD
zone: N.Y.C.
zone: NORTH
zone: NPX
zone: O H
zone: PJM
zone: WEST

In [120]:
records = []
zoneDfs = {zone: df[df['Zone Name'] == zone] for zone in zones}

In [ ]:
for hour in hours:
    #print('Hour:' + str(hour))
    hourDf = zoneDf[zoneDf.Hour == hour]
    for day in days:
        #print('day:' + day)
        records.append({'Date':day,
                        'Hour':hour,
                        'Zone':zone,
                        'LBMP Mean':hourDf[hourDf.DateOfYear == day].LBMP.mean()})

In [111]:
allAveragesDf = pd.DataFrame(records)

In [113]:
allAveragesDf

        Date  Hour  LBMP Mean    Zone
0        8/6     0  23.590000  CAPITL
1        8/7     0  21.227500  CAPITL
2        8/8     0  21.380000  CAPITL
3        8/9     0  20.822500  CAPITL
4       8/10     0  21.490000  CAPITL
5       8/11     0  23.172500  CAPITL
6       8/12     0  24.960000  CAPITL
7       8/13     0  26.015000  CAPITL
8       8/14     0  23.117500  CAPITL
9       8/15     0  24.875000  CAPITL
10      8/16     0  24.213333  CAPITL
11      8/17     0  28.326667  CAPITL
12      8/18     0  25.030000  CAPITL
13      8/19     0  24.276667  CAPITL
14      8/20     0  24.356667  CAPITL
15      8/21     0  24.870000  CAPITL
16      8/22     0  23.710000  CAPITL
17      8/23     0  20.946667  CAPITL
18      8/24     0  20.873333  CAPITL
19      8/25     0  24.730000  CAPITL
20      8/26     0  26.506667  CAPITL
21      8/27     0  27.903333  CAPITL
22      8/28     0  27.190000  CAPITL
23      8/29     0  22.333333  CAPITL
24      8/30     0  22.753333  CAPITL
25      8/31     0  22.503333  CAPITL
26       9/1     0  25.463333  CAPITL
27       9/2     0  25.763333  CAPITL
28       9/3     0  27.220000  CAPITL
29       9/4     0  24.536667  CAPITL
...      ...   ...        ...     ...
131730   7/8    23  21.130000    WEST
131731   7/9    23  18.006667    WEST
131732  7/10    23  17.920000    WEST
131733  7/11    23  18.456667    WEST
131734  7/12    23  21.190000    WEST
131735  7/13    23  22.666667    WEST
131736  7/14    23  21.293333    WEST
131737  7/15    23  21.166667    WEST
131738  7/16    23  19.913333    WEST
131739  7/17    23  20.430000    WEST
131740  7/18    23  22.690000    WEST
131741  7/19    23  24.893333    WEST
131742  7/20    23  24.126667    WEST
131743  7/21    23  24.736667    WEST
131744  7/22    23  23.356667    WEST
131745  7/23    23  22.446667    WEST
131746  7/24    23  21.356667    WEST
131747  7/25    23  22.880000    WEST
131748  7/26    23  23.073333    WEST
131749  7/27    23  23.796667    WEST
131750  7/28    23  23.153333    WEST
131751  7/29    23  23.210000    WEST
131752  7/30    23  20.760000    WEST
131753  7/31    23  21.770000    WEST
131754   8/1    23  22.233333    WEST
131755   8/2    23  22.060000    WEST
131756   8/3    23  23.600000    WEST
131757   8/4    23  21.746667    WEST
131758   8/5    23  18.620000    WEST
131759  2/29    23   9.260000    WEST

[131760 rows x 4 columns]

In [ ]:
format = lambda x: str(x)[:-3]

In [117]:
allAveragesDf[(allAveragesDf["Date"] == '1/1') & (allAveragesDf["Hour"] == 1) & (allAveragesDf["Zone"] == 'CAPITL')]

    Date  Hour  LBMP Mean    Zone
514  1/1     1      31.41  CAPITL